FROM python:3.10.4

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./config /code/config
COPY ./models /code/models
COPY ./routes /code/routes
COPY ./schemas /code/schemas
COPY ./index.py/ /code/

CMD ["uvicorn", "index:app","--reload", "--host", "0.0.0.0", "--port", "80"]

