services:
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.sql:/tmp/mysql-init.sql
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: airflow
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
      MYSQL_DATABASE: airflow
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 2s
      retries: 120
volumes:
  my-db:
